apiVersion: v1
data:
    address: ENC[AES256_GCM,data:vCcwOGkjqw2PfKPDkAO87snAGoA++WXqxgj/LL5c85e8wegc/19z9wcsdBPd+Ns+mjQtiwoHDeDWukHOb67NZOmpna9sx22cwXxYS7F7J13DNWCnmJf1luz+4DCnZJxpHY0qewLSmwsXhuxC,iv:wlTPdWkJGXmfdPuwTo1RAoQPhY5CuVJhMljHtkatXrk=,tag:/9kRCI4mGxgNLpvlQcp8cg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: slack-url
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://test-wi-2.vault.azure.net
        name: tests
        version: 165f83cf23b04003b42375e184796807
        created_at: '2023-03-29T17:16:43Z'
        enc: LlwfFOrBMVtgfKYbzthQHwpSUZlX97jNUqSTGT2182vwZ2DTw2ep_Y8Y1D2l4k59yeB8ziHSUjJhiIw-xzoggxP1nUFEvHVuZOkWilVN6FDubZcCI0Sd9JyMdyqu5auCbk493RfS0SvJR50O3sAeGlboe7oFpaAvQ0ChMcaEDfYolpmXXzZfNE_OJP4wRtHz_f-mLh_DX8yqmG0Jl1yZvHryeWuX5_QZoHtPLHXI-2EiRZR4ryw0A0DYI4RC2B6BtgGfqlfP-SM8a11Eo4bUqtKEkry0fKRHzt7-DrLr5UoL8oWQPsBSSFlUQrSBrEvd1eAqGwpNUIhL7d0pqeobEg
    hc_vault: []
    lastmodified: '2023-03-29T17:16:49Z'
    mac: ENC[AES256_GCM,data:CXjTAp/3ah92BcurFZuZim5r1eNiIQIpD3csCERnbBX9zcUUcUjRcx5xDTdt7iaUoEvmUVlLad5k2ouBy+qYgN6sCAMcVD/XKk1RbaFAeLBb/AENTyXKI1mTpg7rblE8IiQT2jantwak+STfBq85n89w9cTeHCMBL/iR3ByU4ms=,iv:teZ5UxDHxczsWmGFxF5+MxuymtIHV0MJYXA9GOY7A9U=,tag:fcyb9/cDPMmF7uBccGvHMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
