---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: Bucket
metadata:
  name: azure-sas-token
  namespace: flux-system
spec:
  interval: 5m0s
  provider: azure
  bucketName: flux
  endpoint: https://testfluxsaas.blob.core.windows.net