apiVersion: v1
data:
    address: ENC[AES256_GCM,data:Xge/wWs2GPRDGMCk+BGHecrz4C0sU3I5s/o00bEqQbMF9h00ehkIAwIXP4seUp4OMwF3TAfV5HNO0NdU0u9Cea1KOtxXT68bdMeZCkvfpTCB/fKdtC6Pq6pIMJYh0eTXEuTC8oRmRiVcRyVh,iv:7MqeXZUvUrBrwLiXeUnaogNjFXpg7DvLmHQRyU/ODFs=,tag:S6WygiLh5Loae//ZtSzUhw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: slack-url
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://azwi-kv-0fd9.vault.azure.net
        name: test-flux
        version: e37b39374cfe448781582f2db3fdd5de
        created_at: '2023-03-07T12:58:26Z'
        enc: bMqLvgk7nxxyWWEK8zBlBsYQmzobGzCGv5AiP4_B_FSerGwEXTd9GnHy0VNUfjJj-3PXSn5PxkiwCj8GagmyO2a_vQWzEikORflDoqpNM7c4PAGfcj7e353T2Y8y-WeYtBuNyL7OlQc7ydGgdu_neYqIOl0og27YLUQRj-e2raMrgWenn1_zMqAgVtNJ4V7l4KP7_ymgigP_Zerd_u2XTvQaUCmyj8a5Zxh0-tsEewHa61WyzAvtIpQM5bmYKE8WjH9V3yrCdX1REpkDLbd-F7byS5-T7P801YJ75TXHUJHzirJNQtCb2nAyEvn7Ym6blTKD0fOPfeorRjxEaVOSSg
    hc_vault: []
    lastmodified: '2023-03-07T12:58:30Z'
    mac: ENC[AES256_GCM,data:+5045e4g+iUmuDoWgWL+PV7w/mzU4P+YeRVVQUphwm8oMppKqXrR1k6uUpDYzXrbb+PC0m8r9ujYnzP3oVCBmb78fRylQhfTf3zyaFQpxeiVP6PoSgBQlHBQvjtlGcJe1k5FJ65WTsHJJCDXSHGnAvHjI1IKe/i2F3fZM4hckFo=,iv:rUEd1bTDVmCUTBlg+bq5NDVroCxzVTF//rujNXEdb58=,tag:3FhUgfzIXMUp0WqYJq9JRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
