---
apiVersion: v1
kind: Namespace
metadata:
  name: test-${i}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-${i}
  namespace: test-${i}
spec:
  interval: 30m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
    namespace: flux-system
  targetNamespace: test-${i}
  patches:
    - patch: |-
        apiVersion: autoscaling/v2
        kind: HorizontalPodAutoscaler
        metadata:
          name: podinfo
        spec:
          minReplicas: 1
          maxReplicas: 1   
      target:
        kind: HorizontalPodAutoscaler
        name: podinfo
