---
apiVersion: v1
kind: Namespace
metadata:
  name: test-${i}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-${i}
  namespace: test-${i}
spec:
  interval: 5m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
    namespace: flux-system
  targetNamespace: test-${i}
