apiVersion: batch/v1
kind: Job
metadata:
  name: flux-system
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: pi
          image: perl:5.34.2
          command: ["perlx",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4