apiVersion: batch/v1
kind: Job
metadata:
  name: flux-system
  namespace: flux-system
  labels:
    kustomize.toolkit.fluxcd.io/force: enabled
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  template:
    spec:
      containers:
        - name: pi
          image: perl:5.34.1
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Neverx
  backoffLimit: 4