---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 10m0s
  path: ./secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  force: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg