apiVersion: v1
kind: Pod
metadata:
    annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
        password: mine
    labels:
        data: ENC[AES256_GCM,data:wi+Z,iv:RIFjnp6IhaTkDxoKg+UcBrorffUW06X7pFyC17AMcw4=,tag:VxHwy6sR8JaktuY9ELJTAg==,type:str]
        app: podinfo
    name: special
    namespace: flux-system
spec:
    containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:6.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
            - name: http-metrics
              containerPort: 9797
              protocol: TCP
            - name: grpc2
              containerPort: 9991
              protocol: TCP
          command:
            - ./podinfo
            - --port=9898
            - --port-metrics=9797
            - --grpc-port=9999
            - --grpc-service-name=podinfo
            - --level=info
            - --random-delay=false
            - --random-error=false
          env:
            - name: PODINFO_UI_COLOR
              value: '#34577c'
          # - name: EXTRA_KEY
          #   value: "#34577c"
          # envFrom:
          # - secretRef:
          #   name: example
          livenessProbe:
            exec:
                command:
                    - podcli
                    - check
                    - http
                    - localhost:9898/healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            exec:
                command:
                    - podcli
                    - check
                    - http
                    - localhost:9898/readyz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            limits:
                cpu: 2000m
                memory: 512Mi
            requests:
                cpu: 100m
                memory: 64Mi
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/dx-somtoxhi/locations/global/keyRings/sops-demo/cryptoKeys/sops-demo-key
          created_at: "2023-03-13T21:58:11Z"
          enc: CiYACBphu0PbkmFkqapAg06iOFi8Coog38RlomFyefKNfiBSigihGxJJACEM8GQ4ViiLe9MTAKe4zxQSBgQAliqUzSaxL0s61lw007C1dANRTQWQO77/WXNYdwb2bFtgU/8u0M0Cr9onOUo1oim9Tmq8yw==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-13T21:58:13Z"
    mac: ENC[AES256_GCM,data:tUSe36UJrIZOHLN6O/pCkceej/uee/7kVnDcML6zNIlXF/kkiDWtFmkm4zJhKCXxx9mHfEMrzwgW5CNhEDNsklcE7W681phSFc6Xnxo6tY+LDayqHttnFH52Mt6piN9/KS30jFACiLbOGHZYc+BaVzz/xeCLATBIQUSAVhkN2JM=,iv:Gt3Gpg3FkG7uWtLyZFRC4rdCHO3XGPnXNAJiDnkgAsI=,tag:+xtKsf+6ASRykZ3VOE6FUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1