---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  image: gcr.io/dx-somtoxhi/podinfo
  interval: 5m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: podinfo
  policy:
    semver:
      range: '>=7.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: podinfo-acr
  namespace: flux-system
spec:
  image: asia-southeast1-docker.pkg.dev/dx-somtoxhi/podinfo/podinfo
  interval: 5m0s
  provider: gcp

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: podinfo-acr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: podinfo-acr
  policy:
    semver:
      range: '>=6.0.0'

