apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: webapp
  namespace: flux-system
spec:
  type: github
  events:
    - "ping"
    - "push"
    - "star"
  secretRef:
    name: webhook-token
  resources:
    - kind: ImageRepository
      name: *
      namespace: default
      matchLabels:
        label: app