apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sandbox
  namespace: default
  labels:
    app: sandbox
spec:
  minReadySeconds: 10
  serviceName: sandbox
  replicas: 2
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
        - name: nginx
          image: nginx
          # args:
          #   - sleep
          #   - infinity
          # imagePullPolicy: IfNotPresent
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
