apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sandbox
  labels:
    app: sandbox
spec:
  minReadySeconds: 10
  serviceName: sandbox
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
        - name: sandbox
          image: sandbox
          args:
            - sleep
            - infinity
          imagePullPolicy: IfNotPresent
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
