apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- pvc.yaml
patches:
  - target:
      version: v1
      kind: Service
      name: notification-controller
      namespace: flux-system
    patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: notification-controller
        namespace: flux-system
      spec:
        type: LoadBalancer
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: image-reflector-controller
      namespace: flux-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --gcp-autologin-for-gcr    
  - path: sc-patch.json
    target:
      kind: Deployment
      name: source-controller
      namespace: flux-system
  - target:
      version: v1beta2
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      name: flux-system
      namespace: flux-system
    patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        decryption:
          provider: sops
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: kustomize-controller
      namespace: flux-system
      annotations:
        iam.gke.io/gcp-service-account: gcp-kms-365@dx-somtoxhi.iam.gserviceaccount.com  
  # - |-
  #   $patch: delete
  #   apiVersion: apps/v1
  #   kind: Deployment
  #   metadata:
  #     name: notification-controller
  #     namespace: flux-system

images:
  - name: ghcr.io/fluxcd/kustomize-controller
    newName: somma/source-controller
    newTag: artifact-2a4e
  - name: ghcr.io/fluxcd/notification-controller
    newName: somma/notification-controller
    newTag: digest-94740b4
  - name: ghcr.io/fluxcd/source-controller
    newName: somma/source-controller
    newTag: digest-a8fc26c
  - name: ghcr.io/fluxcd/helm-controller
    newTag: rc-0bfbc3ee
