apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - target:
      version: v1
      kind: Service
      name: notification-controller
      namespace: flux-system
    patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: notification-controller
        namespace: flux-system
      spec:
        type: LoadBalancer
  - path: patch.yaml
  - path: sc-patch.yaml
images:
  - name: ghcr.io/fluxcd/kustomize-controller
    newName: somma/kustomize-controller
    newTag: artifact-2a4e
  - name: ghcr.io/fluxcd/notification-controller
    newName: somma/notification-controller
    newTag: digest-94740b4
  - name: ghcr.io/fluxcd/source-controller
    newName: somma/source-controller
    newTag: digest-a8fc26c

