apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
          verify:
            mode: head
            secretRef:
              name: flux-gpg-pubkeys
    target:
      kind: GitRepository
      name: flux-system
      namespace: flux-system