---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pv-svc
