---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-monitoring
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: nc-v1beta3
  url: https://github.com/fluxcd/flux2-monitoring-example
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./kube-prometheus-stack
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-config
  namespace: flux-system
spec:
  dependsOn:
  - name: kube-prometheus-stack
  interval: 1h0m0s
  path: ./monitoring-config
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
