---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flaggerr
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://flagger.app
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: flux-system
spec:
  chart:
    spec:
      interval: 1m0s
      chart: flagger
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: flaggerr
#        namespace: default
      version: '1.26.0'
  interval: 1h
  values:
    resource:
      limit:
        memory: 1Gi
